version: '3.8'

services:
  # db:
  #   image: postgres:15
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: myapp_development
  #   networks:
  #     - app-network

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    # depends_on:
    #   - db
    # environment:
    #   DATABASE_HOST: db
    #   DATABASE_USERNAME: postgres
    #   DATABASE_PASSWORD: password
    # networks:
    #   - app-network

# volumes:
#   postgres_data:

networks:
  app-network:
